// Copyright 2024 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func cmdBpftrace(args []string) {
	fs := flag.NewFlagSet("bpftrace", flag.ExitOnError)
	provider := fs.String("provider", "", "filter by provider name")
	probeName := fs.String("probe", "", "filter by probe name")
	useUprobe := fs.Bool("uprobe", true, "use uprobe syntax (required for static binaries)")

	fs.Usage = func() {
		fmt.Fprintf(os.Stderr, `Usage: go tool usdt bpftrace [flags] <binary>

Generate bpftrace script for USDT probes in a Go binary.

Since Go produces statically linked binaries, the standard USDT discovery
(usdt:/path:provider:name) doesn't work. This command generates bpftrace
scripts using uprobe syntax with the actual probe addresses.

Flags:
`)
		fs.PrintDefaults()
	}

	fs.Parse(args)
	if fs.NArg() != 1 {
		fs.Usage()
		os.Exit(2)
	}

	filename := fs.Arg(0)
	probes, err := ParseProbes(filename)
	if err != nil {
		fmt.Fprintf(os.Stderr, "usdt bpftrace: %v\n", err)
		os.Exit(1)
	}

	if len(probes) == 0 {
		fmt.Fprintln(os.Stderr, "No USDT probes found in binary.")
		os.Exit(0)
	}

	// Filter probes
	var filtered []Probe
	for _, p := range probes {
		if *provider != "" && p.Provider != *provider {
			continue
		}
		if *probeName != "" && p.Name != *probeName {
			continue
		}
		filtered = append(filtered, p)
	}

	if len(filtered) == 0 {
		fmt.Fprintln(os.Stderr, "No probes match the filter criteria.")
		os.Exit(0)
	}

	absPath, err := filepath.Abs(filename)
	if err != nil {
		absPath = filename
	}

	generateBpftraceScript(filtered, absPath, *useUprobe)
}

func generateBpftraceScript(probes []Probe, binaryPath string, useUprobe bool) {
	fmt.Println("#!/usr/bin/env bpftrace")
	fmt.Println("// Generated by: go tool usdt bpftrace")
	fmt.Printf("// Binary: %s\n", binaryPath)
	fmt.Printf("// Probes: %d\n", len(probes))
	fmt.Println("//")
	fmt.Println("// Usage: sudo bpftrace <script.bt>")
	fmt.Println("// Or: sudo bpftrace -e '<one-liner>'")
	fmt.Println()

	for _, p := range probes {
		fmt.Printf("// Probe: %s:%s\n", p.Provider, p.Name)
		if p.ArgDesc != "" {
			fmt.Printf("// Arguments: %s\n", p.ArgDesc)
		}

		if useUprobe {
			fmt.Printf("uprobe:%s:0x%x\n", binaryPath, p.Address)
		} else {
			// Standard USDT syntax (may not work for static binaries)
			fmt.Printf("usdt:%s:%s:%s\n", binaryPath, p.Provider, p.Name)
		}

		fmt.Println("{")
		generateProbeBody(p)
		fmt.Println("}")
		fmt.Println()
	}

	// Add helpful comments about argument access
	fmt.Println("/*")
	fmt.Println("Argument Access Reference:")
	fmt.Println("==========================")
	fmt.Println()
	fmt.Println("With uprobe syntax, arguments are in registers:")
	fmt.Println()
	fmt.Println("AMD64 calling convention:")
	fmt.Println("  arg0: reg(\"di\")  or  @arg0")
	fmt.Println("  arg1: reg(\"si\")  or  @arg1")
	fmt.Println("  arg2: reg(\"dx\")  or  @arg2")
	fmt.Println("  arg3: reg(\"cx\")  or  @arg3")
	fmt.Println()
	fmt.Println("ARM64 calling convention:")
	fmt.Println("  arg0: reg(\"x0\")  or  @arg0")
	fmt.Println("  arg1: reg(\"x1\")  or  @arg1")
	fmt.Println("  arg2: reg(\"x2\")  or  @arg2")
	fmt.Println("  arg3: reg(\"x3\")  or  @arg3")
	fmt.Println()
	fmt.Println("For string pointers, use:")
	fmt.Println("  str(reg(\"di\"), reg(\"si\"))  // pointer in di, length in si")
	fmt.Println()
	fmt.Println("Example: Print HTTP method and path")
	os.Stdout.WriteString("  printf(\"method: %s, path: %s\\n\",\n")
	os.Stdout.WriteString("         str(reg(\"di\"), reg(\"si\")),\n")
	os.Stdout.WriteString("         str(reg(\"dx\"), reg(\"cx\")));\n")
	fmt.Println("*/")
}

func generateProbeBody(p Probe) {
	// Parse argument descriptor to generate helpful access code
	if p.ArgDesc == "" {
		fmt.Printf("    printf(\"%s:%s triggered\\n\");\n", p.Provider, p.Name)
		return
	}

	args := parseArgDesc(p.ArgDesc)
	if len(args) == 0 {
		fmt.Printf("    printf(\"%s:%s triggered\\n\");\n", p.Provider, p.Name)
		return
	}

	// Generate argument printing
	fmt.Printf("    printf(\"%s:%s", p.Provider, p.Name)
	for i := range args {
		fmt.Printf(" arg%d=%%d", i)
	}
	fmt.Print("\\n\"")
	for i, arg := range args {
		fmt.Printf(", %s", argAccessCode(arg, i))
	}
	fmt.Println(");")
}

// ArgInfo represents a parsed argument from ArgDesc.
type ArgInfo struct {
	Size     int    // Size in bytes (negative for signed)
	Register string // Register name
}

func parseArgDesc(desc string) []ArgInfo {
	if desc == "" {
		return nil
	}

	var args []ArgInfo
	parts := strings.Fields(desc)
	for _, part := range parts {
		// Format: "-4@%eax" or "8@x0"
		atIdx := strings.Index(part, "@")
		if atIdx == -1 {
			continue
		}

		sizeStr := part[:atIdx]
		reg := strings.TrimPrefix(part[atIdx+1:], "%")

		var size int
		fmt.Sscanf(sizeStr, "%d", &size)

		args = append(args, ArgInfo{
			Size:     size,
			Register: reg,
		})
	}
	return args
}

func argAccessCode(arg ArgInfo, idx int) string {
	// Map common register names to bpftrace access
	reg := strings.ToLower(arg.Register)

	// AMD64 registers
	amd64Map := map[string]string{
		"rax": "reg(\"ax\")", "eax": "reg(\"ax\")", "ax": "reg(\"ax\")",
		"rbx": "reg(\"bx\")", "ebx": "reg(\"bx\")", "bx": "reg(\"bx\")",
		"rcx": "reg(\"cx\")", "ecx": "reg(\"cx\")", "cx": "reg(\"cx\")",
		"rdx": "reg(\"dx\")", "edx": "reg(\"dx\")", "dx": "reg(\"dx\")",
		"rsi": "reg(\"si\")", "esi": "reg(\"si\")", "si": "reg(\"si\")",
		"rdi": "reg(\"di\")", "edi": "reg(\"di\")", "di": "reg(\"di\")",
		"r8":  "reg(\"r8\")", "r8d": "reg(\"r8\")",
		"r9":  "reg(\"r9\")", "r9d": "reg(\"r9\")",
		"r10": "reg(\"r10\")", "r10d": "reg(\"r10\")",
		"r11": "reg(\"r11\")", "r11d": "reg(\"r11\")",
	}

	// ARM64 registers
	arm64Map := map[string]string{
		"x0": "reg(\"x0\")", "w0": "reg(\"x0\")",
		"x1": "reg(\"x1\")", "w1": "reg(\"x1\")",
		"x2": "reg(\"x2\")", "w2": "reg(\"x2\")",
		"x3": "reg(\"x3\")", "w3": "reg(\"x3\")",
		"x4": "reg(\"x4\")", "w4": "reg(\"x4\")",
		"x5": "reg(\"x5\")", "w5": "reg(\"x5\")",
		"x6": "reg(\"x6\")", "w6": "reg(\"x6\")",
		"x7": "reg(\"x7\")", "w7": "reg(\"x7\")",
	}

	if code, ok := amd64Map[reg]; ok {
		return code
	}
	if code, ok := arm64Map[reg]; ok {
		return code
	}

	// Fallback to generic arg access
	return fmt.Sprintf("arg%d", idx)
}
